# Generated by Django 2.2.3 on 2019-07-02 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=200)),
                ('Hotel_Location', models.CharField(max_length=500)),
                ('Hotel_Country', models.CharField(max_length=500, null=True)),
                ('TotalSentMoney', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Description', models.TextField(null=True)),
                ('CompanyAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SingleBedCount', models.DecimalField(decimal_places=0, max_digits=1)),
                ('DoubleBedCount', models.DecimalField(decimal_places=0, max_digits=1)),
                ('RoomType', models.CharField(max_length=100)),
                ('AirConditioner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Complimentary_Breakfast', models.BooleanField()),
                ('Wifi', models.BooleanField()),
                ('Checkin_Date', models.DateField(null=True)),
                ('Checkout_Date', models.DateField(null=True)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Hotel')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Room')),
            ],
        ),
    ]
