# Generated by Django 2.2.3 on 2019-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190716_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking',
            name='TotalRooms',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
