# Generated by Django 2.2.3 on 2019-07-30 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_auto_20190723_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='DaysCount',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Cancellation_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Booking')),
            ],
        ),
    ]
