# Generated by Django 2.2.3 on 2019-07-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_booking_ifcancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ifCancelled',
            new_name='isCancelled',
        ),
    ]
