# Generated by Django 2.2.3 on 2019-07-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190730_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_log',
            name='notified',
            field=models.BooleanField(default=0),
        ),
    ]
