# Generated by Django 2.2.3 on 2019-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_cancellation_log_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Latitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Longitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='TotalSentMoney',
            field=models.IntegerField(default=0),
        ),
    ]
