# Generated by Django 2.2.3 on 2019-08-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190818_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='Start_Date',
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='Percentage_refunding',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='hotel_room',
            name='Cancellation_Policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Cancellation_Policy'),
        ),
        migrations.AlterField(
            model_name='hotel_room',
            name='Price',
            field=models.FloatField(),
        ),
    ]
