# Generated by Django 2.2.3 on 2019-08-18 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0016_auto_20190818_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Cancellation_Policy',
        ),
        migrations.RemoveField(
            model_name='flight_booking',
            name='Flight_Route',
        ),
        migrations.AddField(
            model_name='booking',
            name='PaidMoney',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='TotalSeats',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='Flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Flight_Route'),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='TotalSeats',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='flight_route',
            name='Cancellation_Policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Cancellation_Policy'),
        ),
        migrations.AddField(
            model_name='flight_route',
            name='TotalSeatsBooked',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air_company',
            name='Percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='air_company',
            name='TotalSentMoney',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='MoneyToPay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='MoneyToRefund',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight_route',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_route',
            name='Duration',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='flight_route',
            name='Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_route',
            name='Time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='Payment_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Booking')),
            ],
        ),
    ]
