# Generated by Django 2.2.5 on 2019-09-03 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0017_auto_20190818_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='TotalSentMoney',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='DoubleBedCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='SingleBedCount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.BooleanField(default=False)),
                ('Message', models.CharField(max_length=100, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Booking')),
            ],
        ),
    ]
