# Generated by Django 2.2.3 on 2019-07-21 14:18

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='userid',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.FileField(upload_to=adminpanel.models.user_directory_path),
        ),
    ]
