# Generated by Django 2.2.3 on 2019-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20190721_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='roomid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photos',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
